//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palette.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palette.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Colours&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;Red&quot;,
        ///      &quot;Colour&quot;: &quot;#FFE52D2D&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Blue&quot;,
        ///      &quot;Colour&quot;: &quot;#FF2D2DE5&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Green&quot;,
        ///      &quot;Colour&quot;: &quot;#FF2DE52D&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;GreenDisabled&quot;,
        ///      &quot;Colour&quot;: &quot;#FF59B259&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Order1&quot;,
        ///      &quot;Colour&quot;: &quot;#FFCDCD32&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Order2&quot;,
        ///      &quot;Colour&quot;: &quot;#FF2794CC&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Order3&quot;,
        ///      &quot;Colour&quot;: &quot;#FFCC28CC&quot;
        ///    },
        ///    {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SamplePalette {
            get {
                return ResourceManager.GetString("SamplePalette", resourceCulture);
            }
        }
    }
}
